### ISSUE TITLE
游戏在启动时崩溃

### ISSUE THREAD

**Issue by Omgise** [AmarokIce/WheatfieldWithWolf-Core#1]
![image](https://github.com/AmarokIce/WheatfieldWithWolf-Core/assets/106000018/3a456783-0cc2-4df4-be56-f3490fa1fe4d)
[crash-2024-02-20_09.52.51-client.txt](https://github.com/AmarokIce/WheatfieldWithWolf-Core/files/14338440/crash-2024-02-20_09.52.51-client.txt)
[fml-client-latest.log](https://github.com/AmarokIce/WheatfieldWithWolf-Core/files/14338441/fml-client-latest.log)

**Comment by Omgise** [comment]
@AmarokIce  可以帮忙看看吗（

**Comment by AmarokIce** [comment]
奇怪的问题，可能是我上传了开发版的Jar导致的，我很快将会重新上传正确的可游玩版本

**Comment by Omgise** [comment]
好的，现在没有崩溃了，谢谢
