### ISSUE TITLE
作物贴图错误

### ISSUE THREAD

**Issue by Omgise** [AmarokIce/WheatfieldWithWolf-Core#2]
![image](https://github.com/AmarokIce/WheatfieldWithWolf-Core/assets/106000018/07666bec-4397-4e69-a8be-f3359b1ffc4e)

**Comment by AmarokIce** [comment]
怪问题，可能是出现了问题，很快就会检查与修正，感谢你的反馈！

**Comment by Omgise** [comment]
检查了一下，就只有草莓，西蓝花，茶叶的作物贴图错误，还有墨西哥辣椒种子种不到地上。

**Comment by AmarokIce** [comment]
了解，非常感谢反馈！会尽快解决
辣椒预设是地狱作物，目前正在计划野生作物，辣椒的获取方式也会改为地狱生成野生作物，其种子需要种植在灵魂沙上

**Comment by AmarokIce** [comment]
已在Fix2中修正，此Issue将会关闭
