### ISSUE TITLE
可以添加午餐盒吗？

### ISSUE THREAD

**Issue by Omgise** [AmarokIce/WheatfieldWithWolf-Core#3]

**Comment by AmarokIce** [comment]
好建议！立刻就开始准备存储食物后可以直接食用的午餐袋与午餐盒！
非常感谢你的提议！

**Comment by AmarokIce** [comment]
已在 Day-2 中更新：
- 午餐袋：
  - 手持午餐袋蹲下可以打开GUI
  - 午餐袋内允许加入三种（组）食物，任意模组添加的食物（继承ItemFood）都可以被兼容
  - 长按右键开始食用午餐袋内的食物，恢复的饥饿值与饱食度将会兼容食物
  - 午餐袋兼容食物食用后效果
